// paintings.js — Curated nocturne painting database
// All images: confirmed public domain via Wikimedia Commons or Met Open Access
// phase: one or more of "new","waxing_crescent","first_quarter","waxing_gibbous",
//         "full","waning_gibbous","last_quarter","waning_crescent"
//         null = symbolic/unspecified (fallback for all phases)

const PAINTINGS = [
  // ─── Whistler ────────────────────────────────────────────────────────────
  {
    id: "whistler-falling-rocket",
    artist: "James McNeill Whistler",
    title: "Nocturne in Black and Gold: The Falling Rocket",
    year: 1875,
    medium: "Oil on panel",
    museum: "Detroit Institute of Arts",
    museumUrl: "https://dia.org/collection/nocturne-black-and-gold-falling-rocket/64931",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Whistler-Nocturne_in_black_and_gold.jpg/960px-Whistler-Nocturne_in_black_and_gold.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Whistler-Nocturne_in_black_and_gold.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["stormy", "cold_blue"],
    palette: "dark",
    description: "This work is a depiction of a fireworks display in London's Cremorne Gardens",
    fact: "It was the central issue of a libel suit that involved the art critic John Ruskin and the artist. Ruskin had publicly slandered the work by making the statement, \"I have seen, and heard, much of cockney impudence before now; but never expected to hear a coxcomb ask two hundred guineas for flinging a pot of paint in the public's face.\"",
  },
  {
    id: "whistler-blue-silver-cremorne",
    artist: "James McNeill Whistler",
    title: "Nocturne: Blue and Silver — Cremorne Lights",
    year: 1872,
    medium: "Oil on canvas",
    museum: "Tate, London",
    museumUrl: "https://www.tate.org.uk/art/artworks/whistler-nocturne-blue-and-silver-cremorne-lights-n03420",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/James_Abbott_McNeill_Whistler_%281834-1903%29_-_Nocturne%2C_Blue_and_Silver_-_Cremorne_Lights_-_N03420_-_National_Gallery.jpg?_=20200703203012",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:James_Abbott_McNeill_Whistler_(1834-1903)_-_Nocturne,_Blue_and_Silver_-_Cremorne_Lights_-_N03420_-_National_Gallery.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["still", "cold_blue"],
    palette: "cold_blue",
    description: "Painted in 1872 by James McNeill Whistler, Nocturne: Blue and Silver — Cremorne Lights is an oil-on-canvas landscape depicting the River Thames at night looking toward Battersea. Housed in the Tate Collection in London, it transforms a polluted industrial riverbank into a tranquil, abstract harmony of tone and light.",
    fact: "X-ray imaging revealed that Whistler originally painted decorative human figures (part of his \"Six Projects\" series) underneath this canvas before painting over them to focus entirely on the nocturnal landscape.",
  },
  {
    id: "whistler-grey-gold-westminster",
    artist: "James McNeill Whistler",
    title: "Nocturne: Grey and Gold — Westminster Bridge",
    year: 1871,
    medium: "Oil on canvas",
    museum: "Burrell Collection, Glasgow",
    museumUrl: "https://commons.wikimedia.org/wiki/File:James_Abbott_McNeill_Whistler_(1834-1903)_-_Nocturne,_Grey_and_Gold,_Westminster_Bridge_-_35.642_-_Burrell_Collection.jpg",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/James_Abbott_McNeill_Whistler_%281834-1903%29_-_Nocturne%2C_Grey_and_Gold%2C_Westminster_Bridge_-_35.642_-_Burrell_Collection.jpg?_=20250504051710",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:James_Abbott_McNeill_Whistler_(1834-1903)_-_Nocturne,_Blue_and_Silver_-_Cremorne_Lights_-_N03420_-_National_Gallery.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["still", "warm_gold"],
    palette: "warm_gold",
    description: "It captures a warm summer night on the River Thames looking toward the London Parliament towers",
    fact: "Whistler named his night scenes \"Nocturnes\" after musical pieces to show that colors and tones mattered more than the actual story or subject.",
  },

  // ─── Van Gogh ────────────────────────────────────────────────────────────
  {
    id: "gogh-starry-night-rhone",
    artist: "Vincent van Gogh",
    title: "Starry Night over the Rhône",
    year: 1888,
    medium: "Oil on canvas",
    museum: "Musée d'Orsay, Paris",
    museumUrl: "https://www.musee-orsay.fr/en/artworks/la-nuit-etoilee-78696",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Starry_Night_Over_the_Rhone.jpg/1280px-Starry_Night_Over_the_Rhone.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Starry_Night_Over_the_Rhone.jpg",
    license: "Public Domain",
    phase: ["full", "waning_gibbous"],
    mood: ["still", "cold_blue"],
    palette: "cold_blue",
    description: "This is a moderately abstract landscape painting (1889) of an expressive night sky over a small hillside village",
    fact: "Unlike his more famous The Starry Night (painted from an asylum window from memory), this piece was painted en plein air (outdoors) on location at night. Astronomers confirmed that the cluster of stars shining over the water accurately maps out the Plough or Ursa Major (Great Bear) constellation as it appeared in Arles that autumn",
  },
  {
    id: "gogh-white-house-night",
    artist: "Vincent van Gogh",
    title: "The White House at Night",
    year: 1890,
    medium: "Oil on canvas",
    museum: "State Hermitage Museum, St. Petersburg",
    museumUrl: "https://www.hermitagemuseum.org/digital-collection/39642?lng=en",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Whitehousenight.jpg/1280px-Whitehousenight.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Whitehousenight.jpg",
    license: "Public Domain",
    phase: ["full", "waxing_gibbous"],
    mood: ["still", "warm_gold"],
    palette: "warm_gold",
    description: "It depicts a lone white cottage glowing under an evening sky featuring a brilliant star (identified by astronomers as Venus) and a lone walking figure, and it hangs in the Hermitage Museum in St. Petersburg",
    fact: "This piece is officially the final night-sky and star-themed painting Vincent van Gogh ever created.",
  },
  {
    id: "gogh-cafe-terrace",
    artist: "Vincent van Gogh",
    title: "Café Terrace at Night",
    year: 1888,
    medium: "Oil on canvas",  
    museum: "Kröller-Müller Museum, Otterlo",
    museumUrl: "https://krollermuller.nl/en/vincent-van-gogh-terrace-of-a-cafe-at-night-place-du-forum-1",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Van_Gogh_-_Terrace_of_a_Caf%C3%A9_at_Night_%28Place_du_Forum%29_1888.jpg/960px-Van_Gogh_-_Terrace_of_a_Caf%C3%A9_at_Night_%28Place_du_Forum%29_1888.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vincent-van-gogh-cafe-terrace-on-the-place-du-forum-arles-at-night-the.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["still", "warm_gold"],
    palette: "warm_gold",
    description: "The oil painting portrays a warm, inviting café terrace glowing beneath a massive yellow gas lantern.",
    fact: "Despite being an evening scene, Van Gogh did not use a single drop of black paint, relying instead on rich blues, violet-pinks, and warm yellows.",
  },

  // ─── Caspar David Friedrich ───────────────────────────────────────────────
  
  {
    id: "friedrich-two-men-moon",
    artist: "Caspar David Friedrich",
    title: " Contemplating the Moon",
    year: 1819,
    medium: "Oil on canvas",
    museum: "The Metropolitan Museum of Art, New York",
    museumUrl: "https://www.metmuseum.org/art/collection/search/438417",
    imageUrl: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/438417/2291693/main-image",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Friedrich_-_Two_Men_Contemplating_the_Moon.jpg",
    license: "Public Domain",
    phase: ["waning_crescent"],
    mood: ["rural", "cold_blue"],
    palette: "cold_blue",
    description: "Two foreground figures stand on a rugged, uphill dirt path framed by an evergreen spruce and an uprooted, gnarled dead oak tree",
    fact: ": Friedrich painted at least three variations of this composition: an 1819–20 version (Galerie Neue Meister, Dresden), a variant featuring a man and woman around 1824 (Alte Nationalgalerie, Berlin), and an 1830 version housed in The Metropolitan Museum of Art. Friedrich joked that if souls migrated to another world after death, he would surely end up \"on the moon\" because he painted it so often",
  },
  {
    id: "friedrich-moonrise-sea",
    artist: "Caspar David Friedrich",
    title: "Moonrise by the Sea",
    year: 1822,
    medium: "Oil on canvas",
    museum: "Alte Nationalgalerie, Berlin & State Hermitage Museum, St. Petersburg",
    museumUrl: "https://www.smb.museum/museen-einrichtungen/alte-nationalgalerie/home/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Caspar_David_Friedrich_-_Moonrise_by_the_Sea_-_WGA08266.jpg/1920px-Caspar_David_Friedrich_-_Moonrise_by_the_Sea_-_WGA08266.jpg?_=20161130220855",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Moonrise_by_the_Sea_-_WGA08266.jpg",
    license: "Public Domain",
    phase: ["waxing_gibbous"],
    mood: ["still", "silver"],
    palette: "silver",
    description: "It shows three silhouetted figures on a boulder watching a golden moon rise over a dark Baltic sea as two ghost-like sailing ships approach the shore",
    fact: "The Lonely Tree, commissioned by banker Joachim Heinrich Wilhelm Wagener to represent evening and morning.",
  },
  {
    id: "friedrich-man-woman-moon",
    artist: "Caspar David Friedrich",
    title: "Man and Woman Contemplating the Moon",
    year: 1824,
    medium: "Oil on canvas",
    museum: "Alte Nationalgalerie, Berlin",
    museumUrl: "https://www.smb.museum/en/museums-institutions/alte-nationalgalerie/home/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Caspar_David_Friedrich_-_Man_and_Woman_Contemplating_the_Moon_-_WGA08271.jpg?_=20110724062504",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Friedrich_-_Two_Men_Contemplating_the_Moon.jpg",
    license: "Public Domain",
    phase: ["waning_crescent"],
    mood: ["rural", "cold_blue"],
    palette: "cold_blue",
    description: "Two foreground figures stand on a rugged, uphill dirt path framed by an evergreen spruce and an uprooted, gnarled dead oak tree",
    fact: "Friedrich painted at least three variations of this composition: an 1819–20 version (Galerie Neue Meister, Dresden), a variant featuring a man and woman around 1824 (Alte Nationalgalerie, Berlin), and an 1830 version housed in The Metropolitan Museum of Art. Friedrich joked that if souls migrated to another world after death, he would surely end up \"on the moon\" because he painted it so often",
  },

  // ─── Edvard Munch ────────────────────────────────────────────────────────
  {
    id: "munch-starry-night",
    artist: "Edvard Munch",
    title: "Starry Night",
    year: 1893,
    medium: "Oil on canvas",
    museum: "J. Paul Getty Museum, Los Angeles",
    museumUrl: "https://www.munch.no/en/edvard-munch/ekely/qr/starry-night/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Edvard_Munch_-_Starry_Night_%281893_Getty%29.jpg/960px-Edvard_Munch_-_Starry_Night_%281893_Getty%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:'Starry_Night'_by_Edvard_Munch,_1893,_Getty_Center.JPG",
    license: "Public Domain",
    phase: null,
    mood: ["cold_blue", "still"],
    palette: "cold_blue",
    description: "Edvard Munch's Starry Night depicts the Norwegian coastal town of Åsgårdstrand under a moody, indigo sky.",
    fact: " A faint, ghostly shape on the fence represents a silhouette of two lovers, a recurring symbol of longing and anxiety in Munch's art",
  },

  // ─── John Atkinson Grimshaw ───────────────────────────────────────────────
  {
    id: "grimshaw-spirit-night",
    artist: "John Atkinson Grimshaw",
    title: "Spirit of the Night",
    year: 1879,
    medium: "Oil on canvas",
    museum: "Private Collection",
    museumUrl: "https://www.christies.com/en/lot/lot-6199667",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/John_Atkinson_Grimshaw_-_Spirit_of_the_Night.jpg/1920px-John_Atkinson_Grimshaw_-_Spirit_of_the_Night.jpg?_=20210123025206",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:John_Atkinson_Grimshaw_-_Spirit_of_the_Night.jpg",
    license: "Public Domain",
    phase: ["full"],
    mood: ["rural", "silver"],
    palette: "silver",
    description: " It depicts an ethereal, translucent-winged fairy draped in a sheer veil, gliding over a moonlit seaside village.",
    fact: "The canvas was originally exhibited with a direct poetic tribute to Percy Bysshe Shelley's verses (\"Wrap thy form in mantle grey / Star in wrought!\")",
  },
  {
    id: "grimshaw-autumnal-evening",
    artist: "John Atkinson Grimshaw",
    title: "Autumnal Evening",
    year: 1882,
    medium: "Oil on board",
    museum: "Private Collection",
    museumUrl: "https://www.christies.com/en/lot/lot-6012075",
    imageUrl: "https://johnatkinsongrimshaw.org/media//b/a/base_32807736.jpg?width=600",
    sourceUrl: "https://johnatkinsongrimshaw.org/An-Autumnal-Evening-Glow.html",
    license: "Public Domain",
    phase: null,
    mood: ["warm_gold", "rural"],
    palette: "warm_gold",
    description: "Autumn Evening, by John Atkinson Grimshaw is an oil-on-canvas painting depicting a quiet, leaf-strewn suburban lane in Leeds, England",
    fact: "Grimshaw was entirely self-taught and used a camera obscura and lenses to project scenes onto his canvas, allowing for his trademark photographic realism",
  },
  {
    id: "grimshaw-liverpool-quay",
    artist: "John Atkinson Grimshaw",
    title: "Reflections on the Thames, Westminster",
    year: 1880,
    medium: "Oil on canvas",
    museum: "Leeds Art Gallery",
    museumUrl: "https://museumsandgalleries.leeds.gov.uk/leeds-art-gallery-jxyz",
    imageUrl: "https://d3d00swyhr67nd.cloudfront.net/w944h944/collection/WYL/LMG/WYL_LMG_99612-001.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Reflections_on_the_Thames,_Westminster_-_Grimshaw,_John_Atkinson.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["warm_gold", "industrial"],
    palette: "warm_gold",
    description: "The masterpiece depicts a moonlit London night featuring the River Thames, the Houses of Parliament, and the iconic clock towe",
    fact: " Renowned artist James Abbott McNeill Whistler famously remarked upon seeing Grimshaw's work: \"I considered myself the inventor of nocturnes until I saw Grimmy's moonlight pictures",
  },
  {
    id: "grimshaw-november-morning",
    artist: "John Atkinson Grimshaw",
    title: "A Moonlit Lane",
    year: 1874,
    medium: "Oil on canvas",
    museum: "Private Collection",
    museumUrl: "https://www.christies.com/en/lot/lot-6104728",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/John_Atkinson_Grimshaw_-_A_moonlit_lane.jpg/960px-John_Atkinson_Grimshaw_-_A_moonlit_lane.jpg?_=20220419172323",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:John_Atkinson_Grimshaw_-_A_moonlit_lane.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["rural", "silver"],
    palette: "silver",
    description: "It is an oil-on-board painting depicting a quiet, deserted rural or suburban lane bathed in the soft, ethereal, and misty glow of a full moon filtering through a delicate cloudscape",
    fact: "Grimshaw was entirely self-taught and used a camera obscura and lenses to project scenes onto his canvas, allowing for his trademark photographic realism",
  },

  // ─── Ralph Albert Blakelock ───────────────────────────────────────────────
  {
    id: "blakelock-moonlight-indian",
    artist: "Ralph Albert Blakelock",
    title: "Moonlight, Indian Encampment",
    year: 1885,
    medium: "Oil on canvas",
    museum: "Smithsonian American Art Museum",
    museumUrl: "https://americanart.si.edu/artwork/moonlight-indian-encampment-2159",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Ralph_Albert_Blakelock_-_Moonlight%2C_Indian_Encampment_-_1929.6.3_-_Smithsonian_American_Art_Museum.jpg?_=20180213000923",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ralph_Albert_Blakelock_-_Moonlight,_Indian_Encampment_-_1929.6.3_-_Smithsonian_American_Art_Museum.jpg",
    license: "Public Domain",
    phase: ["full"],
    mood: ["warm_gold", "rural"],
    palette: "warm_gold",
    description: "Housed in the Smithsonian American Art Museum, it depicts a glowing, eerie moon filtering through dark, silhouetted trees over a quiet Native American camp",
    fact: "Blakelock was an accomplished pianist and would often alternate between playing the piano and painting, using musical improvisation to inspire his hazy nocturnes.",
  },
  {
    id: "blakelock-moonlight",
    artist: "Ralph Albert Blakelock",
    title: "Moonlight",
    year: 1885,
    medium: "Oil on canvas",
    museum: "Brooklyn Museum",
    museumUrl: "https://www.brooklynmuseum.org/en-GB/objects/697",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Ralph_Albert_Blakelock_-_Moonlight_-_Google_Art_Project.jpg/1920px-Ralph_Albert_Blakelock_-_Moonlight_-_Google_Art_Project.jpg?_=20121004210359",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ralph_Albert_Blakelock_-_Moonlight_-_Google_Art_Project.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["warm_gold", "rural"],
    palette: "warm_gold",
    description: "\"Moonlight\" is a signature Tonalist oil painting featuring dark, silhouetted trees against a glowing, luminous moon.",
    fact: "While he was locked away in an asylum, his painting Brook by Moonlight sold for $20,000 in 1916—setting an all-time auction record for a living American artist",
  },

  // ─── Albert Pinkham Ryder ────────────────────────────────────────────────
  {
    id: "ryder-moonlit-cove",
    artist: "Albert Pinkham Ryder",
    title: "Moonlit Cove",
    year: 1880,
    medium: "Oil on canvas",
    museum: "The Phillips Collection, Washington D.C.",
    museumUrl: "https://www.phillipscollection.org/collection/moonlit-cove",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Albert_Pinkham_Ryder_-_Moonlit_Cove_-_Google_Art_Project.jpg/1920px-Albert_Pinkham_Ryder_-_Moonlit_Cove_-_Google_Art_Project.jpg?_=20260407213939",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Albert_Pinkham_Ryder_-_Moonlit_Cove_-_Google_Art_Project.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["silver", "marine"],
    palette: "silver",
    description: "A quiet, nocturnal coastal scene featuring a dark cliff, a calm body of water, and a small moored boat.",
    fact: "Ryder heavily experimented with unconventional and unstable materials—including applying excessive amounts of oil to the backs of his canvases. Because of this eccentric method, Moonlit Cove has significantly darkened and developed extensive surface cracking (crazing) over time.",
  },
  {
    id: "ryder-toilers-sea",
    artist: "Albert Pinkham Ryder",
    title: "Toilers of the Sea",
    year: 1884,
    medium: "Oil on wood",
    museum: "Metropolitan Museum of Art",
    museumUrl: "https://www.metmuseum.org/art/collection/search/11981",
    imageUrl: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/11981/43466/main-image",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Toilers_of_the_Sea_MET_DT228023.jpg",
    license: "Public Domain",
    phase: ["full"],
    mood: ["silver", "marine"],
    palette: "silver",
    description: " A solitary sailboat crests a dark, turbulent wave at night. A bright full moon pierces the heavy atmosphere, casting a strong, pale reflection on the churning sea",
    fact: "The title links the work to Victor Hugo's 1866 novel of the same name. However, Ryder shows no human figures, focusing instead on an emotional and symbolic struggle",
  },

  // ─── Ivan Aivazovsky ────────────────────────────────────────────────────
  {
    id: "aivazovsky-moonlit-black-sea",
    artist: "Ivan Aivazovsky",
    title: "The Black Sea At Night",
    year: 1879,
    medium: "Oil on canvas",
    museum: "Odessa Fine Arts Museum",
    museumUrl: "https://www.ofam.ua/en",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/Ivan_Aivazovsky_-_The_Black_Sea_at_night_(1879).jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ivan_Aivazovsky_-_The_Black_Sea_at_night_(1879).jpg",
    license: "Public Domain",
    phase: ["full", "waning_gibbous"],
    mood: ["silver", "marine"],
    palette: "silver",
    description: "The Black Sea At Night shows a tiny ship drifting on dark, restless waters under a moonlit sky. Clouds break to let moonlight spill across the huge, deep sea, making the water look like a dark and shining mirror",
    fact: "Sailors who saw his art said they could actually \"hear the waves\" moving in his paintings because he painted water so well",
  },
  {
    id: "aivazovsky-night-crimea",
    artist: "Ivan Aivazovsky",
    title: "Moonlit Night in Crimea",
    year: 1859,
    medium: "Oil on canvas",
    museum: "State Russian Museum, St. Petersburg",
    museumUrl: "https://rusmuseumvrm.ru/data/collections/painting/19_20/ayvazovskiy_ik_lunnaya_noch_v_krimu_1859_zh_5878/?lang=en",
    imageUrl: "https://uploads8.wikiart.org/images/ivan-aivazovsky/lunar-night-in-the-crimea-1862.jpg!Large.jpg",
    sourceUrl: "https://www.wikiart.org/en/ivan-aivazovsky/lunar-night-in-the-crimea-1862",
    license: "Public Domain",
    phase: ["waxing_gibbous"],
    mood: ["silver", "marine"],
    palette: "silver",
    description: "\"Moonlit Night in Crimea\" (1859) by Ivan Aivazovsky is a stunning oil painting capturing the peaceful glow of a bright moon reflecting over the dark, gentle waves of the Black Sea,",
    fact: "Aivazovsky rarely sketched outdoors. He painted his glowing water effects and crashing waves entirely from his powerful visual memory. [1]If you woul",
  },

  // ─── Henry Pether ───────────────────────────────────────────────────────
  {
    id: "pether-moonlight-westminster",
    artist: "Henry Pether",
    title: "Westminster Bridge by Moonlight",
    year: 1858,
    medium: "Oil on canvas",
    museum: "Government Art Collection",
    museumUrl: "https://artcollection.culture.gov.uk/artwork/7866/",
    imageUrl: "https://d3d00swyhr67nd.cloudfront.net/w1200h1200/collection/GAC/GAC/GAC_GAC_7866-001.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Henry_Pether_(1800-1880)_-_Westminster_Bridge_by_Moonlight_-_7866_-_Government_Art_Collection.jpg",
    license: "Public Domain",
    phase: ["full"],
    mood: ["warm_gold", "industrial"],
    palette: "warm_gold",
    description: "The piece is an exquisite Victorian nocturne that captures a rapidly modernising London landscape bathed in a dramatic luminous glow",
    fact: "Henry wasn't just a master of painting artificial light; he was actively fascinated by physical light and construction in the real world. Alongside his art career, he was a registered inventor of specialized lamps, architectural tiling, and engineering materials.",
  },

  // ─── Hokusai / Hiroshige ─────────────────────────────────────────────────
  {
    id: "hiroshige-full-moon-takanawa",
    artist: "Utagawa Hiroshige",
    title: "Full Moon at Takanawa",
    year: 1857,
    medium: "Woodblock print",
    museum: "Metropolitan Museum of Art (also at Brooklyn Museum)",
    museumUrl: "https://www.metmuseum.org/art/collection/search/45293",
    imageUrl: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/45293/133566/main-image",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brooklyn_Museum_-_Full_Moon_at_Takanawa_from_Celebrated_Places_in_the_Eastern_Capital_-_Utagawa_Hiroshige_(Ando).jpg",
    license: "Public Domain",
    phase: ["full"],
    mood: ["silver", "marine"],
    palette: "silver",
    description: "This is a classic color woodblock print by Utagawa Hiroshige from his pioneering series Famous Views of the Eastern Capital (Tōto Meisho). It depicts a calm dusk over Edo Bay with a glowing harvest moon and a diagonal sweep of migrating wild geese",
    fact: "Hiroshige dedicates a massive portion of the frame to empty sky and water. This mastery of yohaku (the Japanese aesthetic of intentional negative space) elevates the atmosphere",
  },
  {
    id: "hiroshige-moonlight-nagakubo",
    artist: "Utagawa Hiroshige",
    title: "Nagakubo: Moonlight on the Road",
    year: 1835,
    medium: "Woodblock print",
    museum: "The Metropolitan Museum of Art (also at Cleveland Museum of Art)",
    museumUrl: "https://www.metmuseum.org/art/collection/search/57042",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Utagawa_Hiroshige_-_Nagakubo_(Station_28)_from_the_series_Sixty-Nine_Stations_of_the_Kisokaido_-_1942.144_-_Cleveland_Museum_of_Art.tif/lossy-page1-960px-Utagawa_Hiroshige_-_Nagakubo_(Station_28)_from_the_series_Sixty-Nine_Stations_of_the_Kisokaido_-_1942.144_-_Cleveland_Museum_of_Art.tif.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Utagawa_Hiroshige_-_Nagakubo_(Station_28)_from_the_series_Sixty-Nine_Stations_of_the_Kisokaido_-_1942.144_-_Cleveland_Museum_of_Art.tif",
    license: "Public Domain",
    phase: null,
    mood: ["rural", "cold_blue"],
    palette: "cold_blue",
    description: "It shows travelers silhouetted by moonlight, a traveler crossing a bridge with a walking stick, and children playing with dogs near a man leading a pack horse.",
    fact: "Hiroshige dedicates a massive portion of the frame to empty sky and water. This mastery of yohaku (the Japanese aesthetic of intentional negative space) elevates the atmosphere",
  },
  {
    id: "hokusai-autumn-moon",
    artist: "Katsushika Hokusai",
    title: "Autumn Moon of Ishiyama",
    year: 1804,
    medium: "Woodblock print",
    museum: "Art Institute of Chicago",
    museumUrl: "https://www.artic.edu/artworks/57278",
    imageUrl: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/56898/144514/main-image",
    sourceUrl: null,
    license: "Public Domain",
    phase: ["full"],
    mood: ["silver", "rural"],
    palette: "silver",
    description: "Nagakubo: Moonlight on the Road (Station 27) is a famous woodblock print by Utagawa Hiroshige from his late 1830s series The Sixty-Nine Stations of the Kiso Kaidō.",
    fact: "The print depicts Nagakubo-shuku, an actual mountain post station along the ancient Nakasendō highway in Japan.",
  },

  // ─── George Inness ──────────────────────────────────────────────────────
  {
    id: "inness-moonrise",
    artist: "George Inness",
    title: "Moonrise",
    year: 1887,
    medium: "Oil on canvas",
    museum: "Yale University Art Gallery",
    museumUrl: "https://artgallery.yale.edu/collections/objects/59314",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Moonrise_by_George_Inness_1887.jpeg/1920px-Moonrise_by_George_Inness_1887.jpeg?_=20150811234751",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Moonrise_by_George_Inness_1887.jpeg",
    license: "Public Domain",
    phase: ["waxing_crescent", "first_quarter"],
    mood: ["warm_gold", "rural"],
    palette: "warm_gold",
    description: "It is a quiet twilight landscape showing a pale moon rising over the dark marshes and islands of Alexandria Bay, New York. The oil painting focuses on mood and soft light rather than sharp details",
    fact: "Inness did not care if art looked like a camera photo. He believed a painting should only wake up a deep feeling.",
  },

  // ─── Winslow Homer ──────────────────────────────────────────────────────
  {
    id: "homer-moonlight-wood",
    artist: "Winslow Homer",
    title: "Moonlight, Wood Island Light",
    year: 1894,
    medium: "Oil on canvas",
    museum: "Metropolitan Museum of Art",
    museumUrl: "https://www.metmuseum.org/art/collection/search/11127",
    imageUrl: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/11127/44025/main-image",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Winslow_Homer_-_Moonlight,_Wood_Island_Light.jpg",
    license: "Public Domain",
    phase: ["full"],
    mood: ["silver", "marine"],
    palette: "silver",
    description: "The work shows dark, swelling ocean waves crashing against a rocky coast under a moonlit night sky",
    fact: "Homer never went through formal long-term art academies to learn painting.He trained briefly as a printmaker's apprentice and took a few lessons, but called himself self-taught",
  },

  // ─── Joseph Wright of Derby ──────────────────────────────────────────────
  {
    id: "wright-moonlight-gorge",
    artist: "Joseph Wright of Derby",
    title: "Landscape with a Rainbow",
    year: 1794,
    medium: "Oil on canvas",
    museum: "Derby Museum and Art Gallery",
    museumUrl: "https://www.derbymuseums.org/",
    imageUrl: "https://d3d00swyhr67nd.cloudfront.net/w1200h1200/collection/DBY/DEMAG/DBY_DEMAG_1913_505-001.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Joseph_Wright_of_Derby_(1734-1797)_-_Landscape_with_a_Rainbow_-_1913-505_-_Derby_Museum_and_Art_Gallery.jpg",
    license: "Public Domain",
    phase: null,
    mood: ["warm_gold", "rural"],
    palette: "warm_gold",
    description: "It depicts a serene rural view—framed by dark trees and a rustic bridge—illuminated by a brilliant, colorful rainbow slicing through clearing storm clouds",
    fact: "The painting features a noticeably paler sky enclosed directly within the arc of the rainbow (known as Babinet's reflex/optical phenomenon)—a scientific and meteorological detail of light refraction that scientists did not formally recognize or explain until the following century",
  },

  // ─── Frederic Edwin Church ───────────────────────────────────────────────
  {
    id: "church-moonrise",
    artist: "Frederic Edwin Church",
    title: "Moonrise in Greece",
    year: 1889,
    medium: "Oil on canvas",
    museum: "Santa Barbara Museum of Art",
    museumUrl: "https://collections.sbma.net/objects/1988/moonrise-in-greece?ctx=7f60fbc9a774992d88dc23fc28f0b366f22fdff0&idx=0",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Moonrise_Frederic_Edwin_Church_1889.jpeg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Moonrise_Frederic_Edwin_Church_1889.jpeg",
    license: "Public Domain",
    phase: ["waning_crescent"],
    mood: ["serene", "twilight", "rural"],
    palette: "cool_twilight_with_warm_gold",
    description: "Housed in the Santa Barbara Museum of Art, this landscape portrays ancient classical ruins silhouetted against a dusky twilight as a cool, luminous full moon ascends over a quiet body of water",
    fact: " Church traveled to Greece and toured Athens in 1869, making extensive on-site sketches and oil studies of classical architecture that he drew upon decades late",
  },

  // ─── Jean-François Millet ────────────────────────────────────────────────
  {
    id: "millet-starry-night",
    artist: "Jean-François Millet",
    title: "Starry Night",
    year: 1851,
    medium: "Oil on canvas",
    museum: "Yale University Art Gallery",
    museumUrl: "https://artgallery.yale.edu/collections/objects/52945",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Starry_Night_by_Jean-François_Millet.jpeg/1920px-Starry_Night_by_Jean-François_Millet.jpeg?_=20150811231401",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Starry_Night_by_Jean-Fran%C3%A7ois_Millet.jpeg",
    license: "Public Domain",
    phase: null,
    mood: ["rural", "cold_blue"],
    palette: "cold_blue",
    description: "Its a painting showing a dark rural path, a silhouetted cart on the horizon, and a scientifically accurate night sky filled with shooting stars",
    fact: " Unlike many artists who paint random dots for stars, Millet painted real constellations like Orion's Belt and Canis Major with exact placement",
  },
  // ─── Charles-François Daubigny ───────────────────────────────────────────
  {
    id: "daubigny-moonrise",
    artist: "Charles-François Daubigny",
    title: "Moonrise at Auvers",
    year: 1877,
    medium: "Oil on canvas",
    museum: "Montreal Museum of Fine Arts",
    museumUrl: "https://www.mbam.qc.ca/en/works/4514/",
    imageUrl: "https://mbam.ficelle.app/v1/?src=https%3A%2F%2Fcollections.mbam.qc.ca%2F1919%2FGWeb%2F1919_36_IN3_RET.jpg",
    sourceUrl: "https://www.mbam.qc.ca/en/works/4514/",
    license: "Public Domain",
    phase: ["waxing_gibbous", "full"],
    mood: ["warm_gold", "rural"],
    palette: "warm_gold",
    description: " It captures twilight falling over the French countryside with a luminous full moon rising in the darkening sky.",
    fact: " This atmospheric canvas is widely considered the final major painting completed by Daubigny before his death in February 1878",
  },
];

// Phase matching order (priority: specific match → fallback)
const PHASE_FALLBACK = {
  "new":             ["new", null],
  "waxing_crescent": ["waxing_crescent", null],
  "first_quarter":   ["first_quarter", "waxing_crescent", null],
  "waxing_gibbous":  ["waxing_gibbous", null],
  "full":            ["full", null],
  "waning_gibbous":  ["waning_gibbous", "full", null],
  "last_quarter":    ["last_quarter", "waning_crescent", null],
  "waning_crescent": ["waning_crescent", null],
};

/**
 * Seeded pseudo-random from an integer seed (LCG).
 * Returns a value in [0, 1).
 */
function seededRandom(seed) {
  let s = seed;
  s = (s ^ (s << 13)) >>> 0;
  s = (s ^ (s >> 7)) >>> 0;
  s = (s ^ (s << 17)) >>> 0;
  return (s >>> 0) / 4294967296;
}

/**
 * Pick a painting for the given phase, using a daily seed for consistency.
 * @param {string} phase - current phase key
 * @param {number} daySeed - integer seed (e.g. YYYYMMDD)
 * @returns {Object} painting object
 */
function selectPainting(phase, daySeed, allowUnspecific = true) {
  // If allowUnspecific is false, we strictly search for specific matches first.
  let candidates = PAINTINGS.filter(x => Array.isArray(x.phase) && x.phase.includes(phase));
  
  if (candidates.length === 0 || allowUnspecific) {
    // Merge in phase-unspecific (null) paintings
    const unspecific = PAINTINGS.filter(x => x.phase === null);
    candidates = [...candidates, ...unspecific];
  }

  if (candidates.length > 0) {
    const idx = Math.floor(seededRandom(daySeed) * candidates.length);
    return candidates[idx];
  }

  // Final fallback: any painting
  const idx = Math.floor(seededRandom(daySeed) * PAINTINGS.length);
  return PAINTINGS[idx];
}

export { PAINTINGS, selectPainting, PHASE_FALLBACK };
